version: 1

models:
  - name: fct_prices
    description: "Fact table of real estate transactions for analytics"
    columns:
      - name: transaction_date
        description: "Date of the transaction"
        tests:
          - not_null
      - name: living_area
        description: "Living area of the property"
      - name: rooms
        description: "Number of rooms"
      - name: price
        description: "Price of the property"
        tests:
          - not_null
      - name: latitude
        description: "Latitude of the property"
      - name: longitude
        description: "Longitude of the property"
